# Docker Compose配置文件 - codebuddy2cc
# 用于本地开发和测试环境

version: '3.8'

services:
  codebuddy2cc:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codebuddy2cc
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - CODEBUDDY2CC_AUTH=${CODEBUDDY2CC_AUTH}
      - CODEBUDDY2CC_KEY=${CODEBUDDY2CC_KEY}
      - PORT=${PORT:-8080}
      - DEBUG=${DEBUG:-false}
      - DEBUG_FILE=${DEBUG_FILE:-}
      - CODEBUDDY2CC_UPSTREAM_URL=${CODEBUDDY2CC_UPSTREAM_URL:-}
    env_file:
      - .env
    volumes:
      # 挂载日志目录到宿主机（可选）
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - codebuddy2cc-network

networks:
  codebuddy2cc-network:
    driver: bridge