# Docker Compose配置文件 - codebuddy2cc
# 用于本地开发和测试环境
# 支持BuildKit缓存加速和多架构构建

version: '3.8'

services:
  codebuddy2cc:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
      # BuildKit缓存配置（可选：使用本地缓存）
      # cache_from:
      #   - type=local,src=/tmp/.buildx-cache
      # cache_to:
      #   - type=local,dest=/tmp/.buildx-cache,mode=max
    container_name: codebuddy2cc
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - CODEBUDDY2CC_AUTH=${CODEBUDDY2CC_AUTH}
      - CODEBUDDY2CC_KEY=${CODEBUDDY2CC_KEY}
      - PORT=${PORT:-8080}
      - DEBUG=${DEBUG:-false}
      - DEBUG_FILE=${DEBUG_FILE:-}
      - CODEBUDDY2CC_UPSTREAM_URL=${CODEBUDDY2CC_UPSTREAM_URL:-}
      - GIN_MODE=release
    env_file:
      - .env
    volumes:
      # 挂载日志目录到宿主机（可选）
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - codebuddy2cc-network

networks:
  codebuddy2cc-network:
    driver: bridge